// Generated by CoffeeScript 1.7.1
(function() {
  var active, countries, height, hover, inactive, map, svg, svgHeight, svgWidth, updateWindow, width;

  svg = d3.select('svg');

  height = window.innerHeight;

  width = window.innerWidth;

  svgHeight = svg.attr('height');

  svgWidth = svg.attr('width');

  countries = ['Espagne', 'France', 'Italie', 'Grèce', 'Allemagne', 'Belgique', 'Royaume-Uni', 'Irlande', 'Suède', 'Finlande', 'Norvège'];

  active = '#f5b355';

  inactive = '#f8f8f8';

  hover = '#06A59B';

  updateWindow = function() {
    var temp;
    temp = (svgHeight - height) / 2 + 60;
    return svg.attr('viewBox', '0 ' + temp + ' ' + svgWidth + ' ' + svgHeight);
  };

  window.onresize = function() {
    return updateWindow();
  };

  updateWindow();

  map = {
    changePointer: function() {
      return svg.selectAll('polygon').each(function() {
        console.log('coucou');
        if (d3.select(this).attr('fill') !== inactive) {
          return d3.select(this).style('cursor', 'pointer');
        }
      });
    },
    onMouseOver: function() {
      var country, el;
      map.changePointer();
      el = d3.select(this);
      country = el.attr('data-pays');
      return svg.selectAll('polygon').each(function() {
        if (el.attr('fill') !== inactive && d3.select(this).attr('data-pays') === country) {
          return d3.select(this).attr('fill', hover);
        }
      });
    },
    onMouseLeave: function() {
      return svg.selectAll('polygon').each(function() {
        if (d3.select(this).attr('fill') !== inactive) {
          return d3.select(this).attr('fill', active);
        }
      });
    }
  };

  svg.selectAll('polygon').on('mouseover', map.onMouseOver).on('mouseleave', map.onMouseLeave).each(function() {
    return d3.select(this).attr('fill', function() {
      if (countries.indexOf(d3.select(this).attr('data-pays')) > -1) {
        return active;
      } else {
        return inactive;
      }
    });
  });

}).call(this);
